# Generated by Django 4.2.1 on 2023-05-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimemodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
