# Generated by Django 4.2.1 on 2023-05-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code_finance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code_finance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeDetailMode',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.datetimemodel')),
                ('name_outcome', models.CharField(max_length=500)),
                ('total_outcome', models.IntegerField()),
                ('outcome_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.outcometype')),
            ],
            bases=('common.datetimemodel', models.Model),
        ),
        migrations.CreateModel(
            name='IncomeDetailModel',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.datetimemodel')),
                ('name_income', models.CharField(max_length=500)),
                ('total_income', models.IntegerField()),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.incometype')),
            ],
            bases=('common.datetimemodel', models.Model),
        ),
    ]
